version: 2.1

orbs:
  maven: circleci/maven@1.0.2

jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run: bash jenkins/scripts/deliver.sh
      - persist_to_workspace:
          root: .
          paths:
            - ./

  publish-github-release:
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com//github-release/github-release
            cd artifacts &&  VERSION=$(cat pom.xml | grep "<version>.*</version>" | head -1 |awk -F'[><]' '{print $3}')
            github-release release \
                --user ${CIRCLE_PROJECT_USERNAME} \
                --repo ${CIRCLE_PROJECT_REPONAME}\
                --tag ${VERSION} || echo "Tag '${VERSION}' already exist"
            github-release upload \
            --user ${CIRCLE_PROJECT_USERNAME} \
            --repo ${CIRCLE_PROJECT_REPONAME} \
            --tag ${VERSION} \
            --name "simple-app-jar" \
            --file target/*.jar

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
            tags:
              ignore:
                - /v.*/
      - publish-github-release:
          filters:
            branches:
              only:
                - master
          requires:
            - build
