version: 2.1

orbs:
  maven: circleci/maven@1.0.2
  github-cli: circleci/github-cli@2.0.0


jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run: bash jenkins/scripts/deliver.sh
      - persist_to_workspace:
          root: .
          paths:
            - ./

  publish-github-release:
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - attach_workspace:
          at: .
      - run: VERSION=$(cat artifacts/pom.xml | grep "<version>.*</version>" | head -1 |awk -F'[><]' '{print $3}')
      - gh/release:
          files: target/*.jar
          notes-file: ./changelog.md
          tag: $VERSION

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
            tags:
              ignore:
                - /v.*/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              only:
                - master
            tags:
              ignore:
                - /v.*/
