version: 2.1

orbs:
  maven: circleci/maven@1.0.2
  gh: circleci/github-cli@1.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run: bash jenkins/scripts/deliver.sh
      - persist_to_workspace:
          root: .
          paths:
            - ./
  

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
            tags:
              ignore:
                - /v.*/
      - gh/release:
          pre-steps:
            - attach_workspace:
                at: .
            - run: 
                command: |
                  VERSION=$(cat pom.xml | grep "<version>.*</version>" | head -1 |awk -F'[><]' '{print $3}')  
          filters:
            branches:
              only:
                - master
          notes-file: changelog.md
          requires:
            - build
          tag: ${VERSION}
          title: The initial release
