version: 2.1

orbs:
  maven: circleci/maven@1.0.2
  gh: circleci/github-cli@1.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run: bash jenkins/scripts/deliver.sh
      - persist_to_workspace:
          root: .
          paths:
            - ./
      - run: VERSION=$(cat pom.xml | grep "<version>.*</version>" | head -1 |awk -F'[><]' '{print $3}')

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
            tags:
              ignore:
                - /v.*/
      - gh/release:
          filters:
            branches:
              only:
                - main
          notes-file: changelog.md
          requires:
            - build
          tag: $VERSION
          title: The initial release
